container:
  image: cirrusci/android-sdk:26

check_task:
  gradle_cache:
    folder: ~/.gradle/caches/
  check_script:
    - ./gradlew check jacocoTestReport
    - curl -s https://codecov.io/bash | bash
  before_cache_script:
    # Gradle creates lock files on every run which makes the cache "different" for every build
    - find ~/.gradle/caches/ -name "*.lock" -type f -delete